---
cluster_name:   k8sdc
interface:      eth0
main_ip:        "{{ hostvars[inventory_hostname]['ansible_' + interface].ipv4.address }}"
api_server_ip:  "{{ hostvars[groups['k8sdc-master'][0]]['ansible_' + interface].ipv4.address }}"
use_firewalld:  no
admin_user:     k8admin
admin_uid:      5000
admin_group:    k8admin
admin_gid:      5000
private_key:    "{{ playbook_dir}}/keys/sample_admin_private.pem"
public_key:     "{{ playbook_dir}}/keys/sample_admin_public.pub"
fileserver:     "{{ groups.fileserver | first }}"
download_dir:   /var/download/
install_pkgs:   true
packages:
  - socat
  - ceph-common
install_nfs: true
kubernetes_api_port:     6443
docker_registry_cache: 192.168.1.201:5000
registries:
  - gcr.io
  - kube-registry:5000

# Cluster Services
kubernetes_dns_ip:          10.254.1.1
kubernetes_dns_domain:      k8sdc.io
kubernetes_dns_replicas:    1
kubernetes_registry_ip:     10.254.1.2
kubernetes_install_logging: yes
kubernetes_logging_ip:      10.254.1.3
kubernetes_logging_fqdn:    logging.cluster.k8sdc.io
kubernetes_install_kube_ui: yes
kubernetes_kube_ui_ip:      10.254.1.4
kubernetes_kube_ui_fqdn:    kube-ui.cluster.k8sdc.io

# Infrastructure Services
k8sdc_opendj_ip:         10.254.2.1

# Development Services
k8sdc_install_jenkins:     yes
k8sdc_jenkins_ip:          10.254.3.1
k8sdc_jenkins_fqdn:        jenkins.development.k8sdc.io
k8sdc_install_artifactory: yes
k8sdc_artifactory_ip:      10.254.3.2
k8sdc_artifactory_fqdn:    artifactory.development.k8sdc.io

# Productivity Services


# Application Examples