apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8sdc-prometheus
  namespace: {{ .Values.namespace }}
  labels:
    solution: m1_metrics
    product:  prometheus
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      solution: m1_metrics
      product:  prometheus
