apiVersion: v1
kind: Service
metadata:
  name: k8sdc-prom-node-exporter
  namespace: {{ .Values.namespace }}
  labels:
    solution: m1_metrics
    product:  prometheus-node-exporter
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    prometheus.io/scrape: 'true'
spec:
  clusterIP: None
  selector:
    solution: m1_metrics
    product:  prometheus-node-exporter
  ports:
  - name:       prometheus-node-exporter
    port:       9100
    protocol:   TCP