apiVersion: v1
kind: Service
metadata:
  name: k8sdc-prometheus
  namespace: {{ .Values.namespace }}
  labels:
    solution: m1_metrics
    product:  prometheus
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    solution: m1_metrics
    product:  prometheus
  ports:
  - name: http
    port: 9090
    targetPort: http
    protocol: TCP