apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sdc-ceph-mon-2
  namespace: k8sdc-system
  labels:
    app: k8sdc-ceph-mon-2
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: k8sdc-ceph-mon-2
  strategy: {'type': 'Recreate'}
  template:
    metadata:
      labels:
        app: k8sdc-ceph-mon-2
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: node3.k8sdc.io
      containers:
      - name: k8sdc-ceph-mon-2
        image: ceph/daemon
        args:
          - mon
        env:
          - name:  MON_IP
            value: "192.168.1.213"
          - name:  CEPH_PUBLIC_NETWORK
            value: "0.0.0.0/0"
          - name:  KV_TYPE
            value: "etcd"
          - name:  KV_IP
            value: "127.0.0.1"
          - name:  KV_PORT
            value: "2379" 
        volumeMounts:
          - name: etc
            mountPath: /etc/ceph
          - name: var
            mountPath: /var/lib/ceph
      volumes:
        - name: etc
          hostPath:
            path: /etc/ceph
        - name: var
          hostPath:
            path: /var/lib/ceph
        
