apiVersion: batch/v1
kind: Job
metadata:
  name: k8sdc-ceph-job
  namespace: k8sdc-infra
spec:
  template:
    metadata:
      name: k8sdc-ceph-job
    spec:
      hostNetwork: true
      containers:
      - name: k8sdc-ceph-job
        image: ceph/daemon
        args:
          - populate_kvstore
        env:
          - name: KV_TYPE
            value: "etcd"
          - name: KV_IP
            value: "127.0.0.1"
          - name: KV_PORT
            value: "2379"
      restartPolicy: Never