apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8sdc-jenkins
  namespace: {{ .Values.namespace }}
  labels:
    solution: jm1_job_management
    product:  jenkins
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: k8sdc-jenkins
          servicePort: 8080
