apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8sdc-jenkins
  namespace: {{ .Values.namespace }}
  labels:
    solution: jm1_job_management
    product:  jenkins
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      solution: jm1_job_management
      product:  jenkins
