apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sdc-traefik
  namespace: {{ .Values.namespace }}
  labels:
    solution: hrp1_https_reverse_proxy
    product:  traefik
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  traefik.toml: |
    logLevel = "DEBUG"
    defaultEntryPoints = ["http", "https"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"

      [entryPoints.https]
      address = ":443"

    [web]
    address = ":8080"
    
    [kubernetes]