apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: k8sdc-traefik
  namespace: {{ .Values.namespace }}
  labels:
    solution: hrp1_https_reverse_proxy
    product:  traefik
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      solution: hrp1_https_reverse_proxy
      product:  traefik
  template:
    metadata:
      labels: 
        solution: hrp1_https_reverse_proxy
        product:  traefik
        heritage: {{ .Release.Service | quote }}
        release:  {{ .Release.Name | quote }}
        chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: k8sdc-traefik
          image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.pullPolicy }}
          ports:
            - protocol: TCP
              name: traefik-http
              containerPort: 80
              hostPort: 80
            - protocol: TCP
              name: traefik-https
              containerPort: 443
              hostPort: 443
            - protocol: TCP
              name: traefik-dash
              containerPort: 8080
              # This needs to be changed later so that the admin interface is not available on the hostport
              hostPort: 8080
          volumeMounts:
            - mountPath: /etc/traefik
              name: traefik-toml
      volumes:
        - name: traefik-toml
          configMap:
            name: k8sdc-traefik
