# Default values for cm1_cluster_management.
namespace: kube-system
image: gcr.io/google_containers/kubernetes-dashboard-amd64
tag:   v1.4.0
host:  dashboard.k8sdc.io
externalIP: 192.168.101.110
replicaCount: 1
