# Default values for im1_identity_management.
namespace: k8sdc-infra

opendj_image:     k8sdc/opendj
opendj_tag:       latest

keycloak_image: jboss/keycloak
keycloak_tag:   1.9.3.Final
keycloak_host:  keycloak.k8sdc.io

replicaCount: 1