apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8sdc-keycloak
  namespace: {{ .Values.namespace }}
  labels:
    solution: im1_identity_management
    product:  keycloak
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      solution: im1_identity_management
      product: keycloak
