apiVersion: v1
kind: Service
metadata:
  name: k8sdc-opendj
  namespace: {{ .Values.namespace }}
  labels:
    solution: im1_identity_management
    product:  opendj
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    solution: im1_identity_management
    product:  opendj
  ports:
    - name: ldap
      port: 389
      targetPort: ldap
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: ldaps
      protocol: TCP