---
# cs1_cluster_services solution

- name: cs1_cluster_services | Set variables for deployment
  set_fact:
    variables: >
      namespace={{ solutions.cs1_cluster_services.namespace }},
      domain={{ solutions.cs1_cluster_services.domain }},
      cluster_ip={{ solutions.cs1_cluster_services.cluster_ip }},
      kubedns_image={{ solutions.cs1_cluster_services.images.kubedns.image }},
      kubedns_tag={{ solutions.cs1_cluster_services.images.kubedns.tag }},
      dnsmasq_image={{ solutions.cs1_cluster_services.images.dnsmasq.image }},
      dnsmasq_tag={{ solutions.cs1_cluster_services.images.dnsmasq.tag }},
      healthz_image={{ solutions.cs1_cluster_services.images.healthz.image }},
      healthz_tag={{ solutions.cs1_cluster_services.images.healthz.tag }},
      heapster_image={{ solutions.cs1_cluster_services.images.heapster.image }},
      heapster_image={{ solutions.cs1_cluster_services.images.heapster.image }},
      replicaCount={{ solutions.cs1_cluster_services.replicas }}
  run_once: yes

- name: cs1_cluster_services | Run Helm
  include: helm.yaml sol_name=cs1_cluster_services variables=variables
  delegate_to: localhost
  run_once:    yes
  become:      no

