---
# Create Kubernetes namespaces
- name: main | Get Kubernetes Namespaces
  command: /bin/kubectl get ns
  register: k8s_current_namespaces
  delegate_to:   "{{ groups['k8sdc-masters'][0] }}"
  run_once:      yes
  tags: k8s_ns

- name: main | Create Kubernetes Namespaces
  command:       /bin/kubectl create ns {{ item }}
  environment:
    KUBECONFIG:  /etc/kubernetes/kubeconfig/kubectl.kubeconfig
  delegate_to:   "{{ groups['k8sdc-masters'][0] }}"
  run_once:      yes
  ignore_errors: yes
  with_items:    "{{ k8s_namespaces }}"
  when: item not in k8s_current_namespaces.stdout
  tags: k8s_ns


# cs1_cluster_services
- include: cs1_cluster_services.yaml
  when: solutions.cs1_cluster_services.enable is defined and 
        solutions.cs1_cluster_services.enable
  tags: cs1_cluster_services

# cm1_cluster_management
- include: cm1_cluster_management.yaml
  when: solutions.cm1_cluster_management.enable is defined and 
        solutions.cm1_cluster_management.enable
  tags: cm1_cluster_management

# dbs1_distributed_block_storage
- include: dbs1_distributed_block_storage.yaml
  when: solutions.dbs1_distributed_block_storage.enable is defined and 
        solutions.dbs1_distributed_block_storage.enable
  tags: dbs1_distributed_block_storage

# im1_identity_management
- include: im1_identity_management.yaml
  when: solutions.im1_identity_management.enable is defined and 
        solutions.im1_identity_management.enable 
  tags: im1_identity_management

# hrp1_https_reverse_proxy
- include: hrp1_https_reverse_proxy.yaml
  when: solutions.hrp1_https_reverse_proxy.enable is defined and 
        solutions.hrp1_https_reverse_proxy.enable 
  tags: hrp1_https_reverse_proxy

# m1_metrics
- include: m1_metrics.yaml
  when: solutions.m1_metrics.enable is defined and 
        solutions.m1_metrics.enable 
  tags: m1_metrics
  
# l1_logging

# jm1_job_management
- include: jm1_job_management.yaml
  when: solutions.jm1_job_management.enable is defined and 
        solutions.jm1_job_management.enable 
  tags: jm1_job_management

# as1_artifact_storage

# ir1_image_repository

