---
kubernetes_version:      1.3.5
kubernetes_url:          https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/
kubernetes_uid:          5003
kubernetes_gid:          5013
kubernetes_srv_addr:     10.254.0.0/16
k8s_privileged:   true
kubernetes_admission:    --admission_control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
