---
etcd_version: 3.0.13
etcd_pkgname: etcd-v{{ etcd_version }}-linux-amd64.tar.gz
etcd_url:     https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/{{ etcd_pkgname }}
etcd_uid:     5001
etcd_gid:     5011