---
goos:       "{{ ansible_system | lower }}"
goarch:     amd64
client_dir: /usr/local/bin/

kubectl_http_proxy: ''
kubectl_https_proxy: ''

# kubectl
kubectl_version: 1.4.5
kubectl_host:    https://storage.googleapis.com
kubectl_path: >-
  kubernetes-release/release/v{{ kubectl_version }}/bin/{{ goos }}/{{ goarch }}
kubectl_url:     "{{ kubectl_host }}/{{ kubectl_path }}/kubectl"

# Helm
helm_version: 2.0.0-beta.1
helm_host:    https://storage.googleapis.com
helm_path: >-
  kubernetes-helm/helm-v{{ helm_version }}-{{ goos }}-{{ goarch }}.tar.gz
helm_url:     "{{ helm_host }}/{{ helm_path }}"